# Generated by Django 5.1.4 on 2025-01-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('State', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('state_id', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='State.statemodel')),
            ],
            options={
                'db_table': 'tbl_city',
            },
        ),
    ]
