# Generated by Django 5.1.4 on 2025-01-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0002_ordermodel_address2'),
        ('Products', '0003_rename_img_1_productsmodel_img1_and_more'),
        ('Variant', '0002_remove_variantmodel_products_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='Order.ordermodel')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel')),
                ('variant_id', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, to='Variant.variantmodel')),
            ],
        ),
    ]
