# Generated by Django 5.1.4 on 2025-01-29 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
        ('Order', '0002_ordermodel_address2'),
        ('Products', '0003_rename_img_1_productsmodel_img1_and_more'),
        ('Variant', '0002_remove_variantmodel_products_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='price',
            field=models.FloatField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='qty',
            field=models.FloatField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Order.ordermodel'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='variant_id',
            field=models.ForeignKey(db_column='variant_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Variant.variantmodel'),
        ),
        migrations.AlterModelTable(
            name='itemmodel',
            table='tbl_item',
        ),
    ]
