# Generated by Django 5.1.4 on 2025-04-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('pincode_id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.FloatField(max_length=6)),
            ],
            options={
                'db_table': 'tbl_pincode',
            },
        ),
    ]
