# Generated by Django 5.1.4 on 2025-04-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pincode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StateModel',
            new_name='PincodeModel',
        ),
    ]
