# Generated by Django 5.1.4 on 2025-01-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0002_ordermodel_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='Order.ordermodel')),
            ],
            options={
                'db_table': 'tbl_log',
            },
        ),
    ]
