# Generated by Django 5.1.4 on 2025-01-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
    ]
