# Generated by Django 5.1.4 on 2025-01-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_img_1_productsmodel_img1_and_more'),
        ('Variant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantmodel',
            name='products_id',
        ),
        migrations.AddField(
            model_name='variantmodel',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel'),
        ),
    ]
