# Generated by Django 5.1.4 on 2025-01-29 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Electrician', '0002_remove_electricianmodel_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquriesModel',
            fields=[
                ('inq_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile_num', models.FloatField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('elec_id', models.ForeignKey(db_column='elec_id', on_delete=django.db.models.deletion.CASCADE, to='Electrician.electricianmodel')),
            ],
            options={
                'db_table': 'tbl_inquries',
            },
        ),
    ]
