# Generated by Django 5.1.4 on 2025-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inquries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquriesmodel',
            name='mobile_num',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
