# Generated by Django 5.1.4 on 2025-01-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricianModel',
            fields=[
                ('elec_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('aboutelectrician', models.CharField(max_length=400)),
                ('isactive', models.CharField(max_length=50)),
                ('city_id', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='City.citymodel')),
            ],
            options={
                'db_table': 'tbl_electrician',
            },
        ),
    ]
