# Generated by Django 5.1.4 on 2025-01-28 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
        ('Electrician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricianmodel',
            name='city_name',
        ),
        migrations.AddField(
            model_name='electricianmodel',
            name='mobilenumber',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='electricianmodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electricianmodel',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='City.citymodel'),
        ),
    ]
