# Generated by Django 5.1.4 on 2025-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electrician', '0002_remove_electricianmodel_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricianmodel',
            name='elec_price',
            field=models.FloatField(default=None, max_length=50),
        ),
    ]
