# Generated by Django 5.1.4 on 2025-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_company',
            },
        ),
    ]
