# Generated by Django 5.1.4 on 2025-01-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0003_rename_img_1_productsmodel_img1_and_more'),
        ('User', '0001_initial'),
        ('Variant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
                ('variant_id', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, to='Variant.variantmodel')),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
    ]
