# Generated by Django 5.1.4 on 2025-02-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cartmodel_user_id'),
        ('Variant', '0002_remove_variantmodel_products_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='variant_id',
            field=models.ForeignKey(db_column='variant_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Variant.variantmodel'),
        ),
    ]
