# Generated by Django 5.1.4 on 2025-01-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.FloatField(max_length=10)),
                ('isactive', models.CharField(max_length=10)),
                ('mobile', models.FloatField(max_length=12)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
