# Generated by Django 5.1.4 on 2025-01-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_payment', models.FloatField(max_length=50)),
                ('address1', models.CharField(max_length=400)),
                ('pincode', models.FloatField(max_length=6)),
                ('paytype', models.CharField(max_length=50)),
                ('transaction_number', models.CharField(max_length=100)),
                ('deliverycharge', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
    ]
