# Generated by Django 5.1.4 on 2025-01-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address2',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
