# Generated by Django 5.1.4 on 2025-02-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
        ('Order', '0002_ordermodel_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='City.citymodel'),
        ),
    ]
