# Generated by Django 5.1.4 on 2025-02-24 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_ordermodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='orderdatetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
