# Generated by Django 5.1.4 on 2025-01-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Subcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('retail_price', models.FloatField(max_length=50)),
                ('sell_price', models.FloatField(max_length=50)),
                ('img_1', models.CharField(max_length=50)),
                ('img_2', models.CharField(max_length=50)),
                ('img_3', models.CharField(max_length=50)),
                ('video_url', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('packaging', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='Company.companymodel')),
                ('subcategory_id', models.ForeignKey(db_column='subcategory_id', on_delete=django.db.models.deletion.CASCADE, to='Subcategory.subcategorymodel')),
            ],
            options={
                'db_table': 'tbl_products',
            },
        ),
    ]
