# Generated by Django 5.1.4 on 2025-01-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='img_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='img_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='img_3',
            field=models.CharField(max_length=100),
        ),
    ]
