# Generated by Django 5.1.4 on 2025-01-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_productsmodel_img_1_alter_productsmodel_img_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='img_1',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='productsmodel',
            old_name='img_2',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='productsmodel',
            old_name='img_3',
            new_name='img3',
        ),
        migrations.RenameField(
            model_name='productsmodel',
            old_name='is_active',
            new_name='isactive',
        ),
    ]
